### ISSUE TITLE
🐮 什么时候有树呀~ 在等~

### ISSUE THREAD

**Issue by ghost** [wwyqianqian/ccnu-data-structures#3]

**Comment by wwyqianqian** [comment]
哇好感动！瞬间有动力了！最晚下周四#flag

yiran <notifications@github.com>于2018年11月20日 周二上午12:05写道：

**Comment by wwyqianqian** [comment]
https://github.com/wwyqianqian/ccnu-data-structures/blob/master/unit6-tree/createBiTree.cpp

来了~

**Comment by ghost** [comment]
^~^
